/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AAssignRecStmts extends PStmts
{
    private PAssignStmt _assignStmt_;
    private TNewline _newline_;
    private PStmts _stmts_;

    public AAssignRecStmts()
    {
        // Constructor
    }

    public AAssignRecStmts(
        @SuppressWarnings("hiding") PAssignStmt _assignStmt_,
        @SuppressWarnings("hiding") TNewline _newline_,
        @SuppressWarnings("hiding") PStmts _stmts_)
    {
        // Constructor
        setAssignStmt(_assignStmt_);

        setNewline(_newline_);

        setStmts(_stmts_);

    }

    @Override
    public Object clone()
    {
        return new AAssignRecStmts(
            cloneNode(this._assignStmt_),
            cloneNode(this._newline_),
            cloneNode(this._stmts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignRecStmts(this);
    }

    public PAssignStmt getAssignStmt()
    {
        return this._assignStmt_;
    }

    public void setAssignStmt(PAssignStmt node)
    {
        if(this._assignStmt_ != null)
        {
            this._assignStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignStmt_ = node;
    }

    public TNewline getNewline()
    {
        return this._newline_;
    }

    public void setNewline(TNewline node)
    {
        if(this._newline_ != null)
        {
            this._newline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newline_ = node;
    }

    public PStmts getStmts()
    {
        return this._stmts_;
    }

    public void setStmts(PStmts node)
    {
        if(this._stmts_ != null)
        {
            this._stmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmts_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignStmt_)
            + toString(this._newline_)
            + toString(this._stmts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignStmt_ == child)
        {
            this._assignStmt_ = null;
            return;
        }

        if(this._newline_ == child)
        {
            this._newline_ = null;
            return;
        }

        if(this._stmts_ == child)
        {
            this._stmts_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignStmt_ == oldChild)
        {
            setAssignStmt((PAssignStmt) newChild);
            return;
        }

        if(this._newline_ == oldChild)
        {
            setNewline((TNewline) newChild);
            return;
        }

        if(this._stmts_ == oldChild)
        {
            setStmts((PStmts) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
