/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AAssignAssignStmt extends PAssignStmt
{
    private TId _id_;
    private PEqualStmt _equalStmt_;

    public AAssignAssignStmt()
    {
        // Constructor
    }

    public AAssignAssignStmt(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PEqualStmt _equalStmt_)
    {
        // Constructor
        setId(_id_);

        setEqualStmt(_equalStmt_);

    }

    @Override
    public Object clone()
    {
        return new AAssignAssignStmt(
            cloneNode(this._id_),
            cloneNode(this._equalStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignAssignStmt(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PEqualStmt getEqualStmt()
    {
        return this._equalStmt_;
    }

    public void setEqualStmt(PEqualStmt node)
    {
        if(this._equalStmt_ != null)
        {
            this._equalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._equalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._equalStmt_ == child)
        {
            this._equalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._equalStmt_ == oldChild)
        {
            setEqualStmt((PEqualStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
