/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ABeginBlock extends PBlock
{
    private TLCurly _lCurly_;
    private TNewline _newline_;
    private PStmts _stmts_;
    private PEndblock _endblock_;

    public ABeginBlock()
    {
        // Constructor
    }

    public ABeginBlock(
        @SuppressWarnings("hiding") TLCurly _lCurly_,
        @SuppressWarnings("hiding") TNewline _newline_,
        @SuppressWarnings("hiding") PStmts _stmts_,
        @SuppressWarnings("hiding") PEndblock _endblock_)
    {
        // Constructor
        setLCurly(_lCurly_);

        setNewline(_newline_);

        setStmts(_stmts_);

        setEndblock(_endblock_);

    }

    @Override
    public Object clone()
    {
        return new ABeginBlock(
            cloneNode(this._lCurly_),
            cloneNode(this._newline_),
            cloneNode(this._stmts_),
            cloneNode(this._endblock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABeginBlock(this);
    }

    public TLCurly getLCurly()
    {
        return this._lCurly_;
    }

    public void setLCurly(TLCurly node)
    {
        if(this._lCurly_ != null)
        {
            this._lCurly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCurly_ = node;
    }

    public TNewline getNewline()
    {
        return this._newline_;
    }

    public void setNewline(TNewline node)
    {
        if(this._newline_ != null)
        {
            this._newline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newline_ = node;
    }

    public PStmts getStmts()
    {
        return this._stmts_;
    }

    public void setStmts(PStmts node)
    {
        if(this._stmts_ != null)
        {
            this._stmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmts_ = node;
    }

    public PEndblock getEndblock()
    {
        return this._endblock_;
    }

    public void setEndblock(PEndblock node)
    {
        if(this._endblock_ != null)
        {
            this._endblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lCurly_)
            + toString(this._newline_)
            + toString(this._stmts_)
            + toString(this._endblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lCurly_ == child)
        {
            this._lCurly_ = null;
            return;
        }

        if(this._newline_ == child)
        {
            this._newline_ = null;
            return;
        }

        if(this._stmts_ == child)
        {
            this._stmts_ = null;
            return;
        }

        if(this._endblock_ == child)
        {
            this._endblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lCurly_ == oldChild)
        {
            setLCurly((TLCurly) newChild);
            return;
        }

        if(this._newline_ == oldChild)
        {
            setNewline((TNewline) newChild);
            return;
        }

        if(this._stmts_ == oldChild)
        {
            setStmts((PStmts) newChild);
            return;
        }

        if(this._endblock_ == oldChild)
        {
            setEndblock((PEndblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
