/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ABoolDcl extends PDcl
{
    private TBoolType _boolType_;
    private PAssignStmt _assignStmt_;

    public ABoolDcl()
    {
        // Constructor
    }

    public ABoolDcl(
        @SuppressWarnings("hiding") TBoolType _boolType_,
        @SuppressWarnings("hiding") PAssignStmt _assignStmt_)
    {
        // Constructor
        setBoolType(_boolType_);

        setAssignStmt(_assignStmt_);

    }

    @Override
    public Object clone()
    {
        return new ABoolDcl(
            cloneNode(this._boolType_),
            cloneNode(this._assignStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolDcl(this);
    }

    public TBoolType getBoolType()
    {
        return this._boolType_;
    }

    public void setBoolType(TBoolType node)
    {
        if(this._boolType_ != null)
        {
            this._boolType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolType_ = node;
    }

    public PAssignStmt getAssignStmt()
    {
        return this._assignStmt_;
    }

    public void setAssignStmt(PAssignStmt node)
    {
        if(this._assignStmt_ != null)
        {
            this._assignStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolType_)
            + toString(this._assignStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolType_ == child)
        {
            this._boolType_ = null;
            return;
        }

        if(this._assignStmt_ == child)
        {
            this._assignStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolType_ == oldChild)
        {
            setBoolType((TBoolType) newChild);
            return;
        }

        if(this._assignStmt_ == oldChild)
        {
            setAssignStmt((PAssignStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
