/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ABoolLstType extends PType
{
    private TBoolType _boolType_;
    private TListDcl _listDcl_;

    public ABoolLstType()
    {
        // Constructor
    }

    public ABoolLstType(
        @SuppressWarnings("hiding") TBoolType _boolType_,
        @SuppressWarnings("hiding") TListDcl _listDcl_)
    {
        // Constructor
        setBoolType(_boolType_);

        setListDcl(_listDcl_);

    }

    @Override
    public Object clone()
    {
        return new ABoolLstType(
            cloneNode(this._boolType_),
            cloneNode(this._listDcl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolLstType(this);
    }

    public TBoolType getBoolType()
    {
        return this._boolType_;
    }

    public void setBoolType(TBoolType node)
    {
        if(this._boolType_ != null)
        {
            this._boolType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolType_ = node;
    }

    public TListDcl getListDcl()
    {
        return this._listDcl_;
    }

    public void setListDcl(TListDcl node)
    {
        if(this._listDcl_ != null)
        {
            this._listDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listDcl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolType_)
            + toString(this._listDcl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolType_ == child)
        {
            this._boolType_ = null;
            return;
        }

        if(this._listDcl_ == child)
        {
            this._listDcl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolType_ == oldChild)
        {
            setBoolType((TBoolType) newChild);
            return;
        }

        if(this._listDcl_ == oldChild)
        {
            setListDcl((TListDcl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
