/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACntrolRecStmts extends PStmts
{
    private PCntrol _cntrol_;
    private PStmts _stmts_;

    public ACntrolRecStmts()
    {
        // Constructor
    }

    public ACntrolRecStmts(
        @SuppressWarnings("hiding") PCntrol _cntrol_,
        @SuppressWarnings("hiding") PStmts _stmts_)
    {
        // Constructor
        setCntrol(_cntrol_);

        setStmts(_stmts_);

    }

    @Override
    public Object clone()
    {
        return new ACntrolRecStmts(
            cloneNode(this._cntrol_),
            cloneNode(this._stmts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACntrolRecStmts(this);
    }

    public PCntrol getCntrol()
    {
        return this._cntrol_;
    }

    public void setCntrol(PCntrol node)
    {
        if(this._cntrol_ != null)
        {
            this._cntrol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cntrol_ = node;
    }

    public PStmts getStmts()
    {
        return this._stmts_;
    }

    public void setStmts(PStmts node)
    {
        if(this._stmts_ != null)
        {
            this._stmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmts_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cntrol_)
            + toString(this._stmts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cntrol_ == child)
        {
            this._cntrol_ = null;
            return;
        }

        if(this._stmts_ == child)
        {
            this._stmts_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cntrol_ == oldChild)
        {
            setCntrol((PCntrol) newChild);
            return;
        }

        if(this._stmts_ == oldChild)
        {
            setStmts((PStmts) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
