/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACntrolStmts extends PStmts
{
    private PCntrol _cntrol_;

    public ACntrolStmts()
    {
        // Constructor
    }

    public ACntrolStmts(
        @SuppressWarnings("hiding") PCntrol _cntrol_)
    {
        // Constructor
        setCntrol(_cntrol_);

    }

    @Override
    public Object clone()
    {
        return new ACntrolStmts(
            cloneNode(this._cntrol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACntrolStmts(this);
    }

    public PCntrol getCntrol()
    {
        return this._cntrol_;
    }

    public void setCntrol(PCntrol node)
    {
        if(this._cntrol_ != null)
        {
            this._cntrol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cntrol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cntrol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cntrol_ == child)
        {
            this._cntrol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cntrol_ == oldChild)
        {
            setCntrol((PCntrol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
