/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACond5Cond4 extends PCond4
{
    private PCond5 _cond5_;

    public ACond5Cond4()
    {
        // Constructor
    }

    public ACond5Cond4(
        @SuppressWarnings("hiding") PCond5 _cond5_)
    {
        // Constructor
        setCond5(_cond5_);

    }

    @Override
    public Object clone()
    {
        return new ACond5Cond4(
            cloneNode(this._cond5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACond5Cond4(this);
    }

    public PCond5 getCond5()
    {
        return this._cond5_;
    }

    public void setCond5(PCond5 node)
    {
        if(this._cond5_ != null)
        {
            this._cond5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond5_ == child)
        {
            this._cond5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond5_ == oldChild)
        {
            setCond5((PCond5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
