/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AElseIfElseStmt extends PElseStmt
{
    private TElse _else_;
    private PIfStmt _ifStmt_;

    public AElseIfElseStmt()
    {
        // Constructor
    }

    public AElseIfElseStmt(
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PIfStmt _ifStmt_)
    {
        // Constructor
        setElse(_else_);

        setIfStmt(_ifStmt_);

    }

    @Override
    public Object clone()
    {
        return new AElseIfElseStmt(
            cloneNode(this._else_),
            cloneNode(this._ifStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseIfElseStmt(this);
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PIfStmt getIfStmt()
    {
        return this._ifStmt_;
    }

    public void setIfStmt(PIfStmt node)
    {
        if(this._ifStmt_ != null)
        {
            this._ifStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._else_)
            + toString(this._ifStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._ifStmt_ == child)
        {
            this._ifStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._ifStmt_ == oldChild)
        {
            setIfStmt((PIfStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
