/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AGteCond3 extends PCond3
{
    private PCond4 _cond4_;
    private TGte _gte_;
    private PCond3 _cond3_;

    public AGteCond3()
    {
        // Constructor
    }

    public AGteCond3(
        @SuppressWarnings("hiding") PCond4 _cond4_,
        @SuppressWarnings("hiding") TGte _gte_,
        @SuppressWarnings("hiding") PCond3 _cond3_)
    {
        // Constructor
        setCond4(_cond4_);

        setGte(_gte_);

        setCond3(_cond3_);

    }

    @Override
    public Object clone()
    {
        return new AGteCond3(
            cloneNode(this._cond4_),
            cloneNode(this._gte_),
            cloneNode(this._cond3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGteCond3(this);
    }

    public PCond4 getCond4()
    {
        return this._cond4_;
    }

    public void setCond4(PCond4 node)
    {
        if(this._cond4_ != null)
        {
            this._cond4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond4_ = node;
    }

    public TGte getGte()
    {
        return this._gte_;
    }

    public void setGte(TGte node)
    {
        if(this._gte_ != null)
        {
            this._gte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gte_ = node;
    }

    public PCond3 getCond3()
    {
        return this._cond3_;
    }

    public void setCond3(PCond3 node)
    {
        if(this._cond3_ != null)
        {
            this._cond3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond4_)
            + toString(this._gte_)
            + toString(this._cond3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond4_ == child)
        {
            this._cond4_ = null;
            return;
        }

        if(this._gte_ == child)
        {
            this._gte_ = null;
            return;
        }

        if(this._cond3_ == child)
        {
            this._cond3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond4_ == oldChild)
        {
            setCond4((PCond4) newChild);
            return;
        }

        if(this._gte_ == oldChild)
        {
            setGte((TGte) newChild);
            return;
        }

        if(this._cond3_ == oldChild)
        {
            setCond3((PCond3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
