/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ALteCond3 extends PCond3
{
    private PCond4 _cond4_;
    private TLte _lte_;
    private PCond3 _cond3_;

    public ALteCond3()
    {
        // Constructor
    }

    public ALteCond3(
        @SuppressWarnings("hiding") PCond4 _cond4_,
        @SuppressWarnings("hiding") TLte _lte_,
        @SuppressWarnings("hiding") PCond3 _cond3_)
    {
        // Constructor
        setCond4(_cond4_);

        setLte(_lte_);

        setCond3(_cond3_);

    }

    @Override
    public Object clone()
    {
        return new ALteCond3(
            cloneNode(this._cond4_),
            cloneNode(this._lte_),
            cloneNode(this._cond3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALteCond3(this);
    }

    public PCond4 getCond4()
    {
        return this._cond4_;
    }

    public void setCond4(PCond4 node)
    {
        if(this._cond4_ != null)
        {
            this._cond4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond4_ = node;
    }

    public TLte getLte()
    {
        return this._lte_;
    }

    public void setLte(TLte node)
    {
        if(this._lte_ != null)
        {
            this._lte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lte_ = node;
    }

    public PCond3 getCond3()
    {
        return this._cond3_;
    }

    public void setCond3(PCond3 node)
    {
        if(this._cond3_ != null)
        {
            this._cond3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond4_)
            + toString(this._lte_)
            + toString(this._cond3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond4_ == child)
        {
            this._cond4_ = null;
            return;
        }

        if(this._lte_ == child)
        {
            this._lte_ = null;
            return;
        }

        if(this._cond3_ == child)
        {
            this._cond3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond4_ == oldChild)
        {
            setCond4((PCond4) newChild);
            return;
        }

        if(this._lte_ == oldChild)
        {
            setLte((TLte) newChild);
            return;
        }

        if(this._cond3_ == oldChild)
        {
            setCond3((PCond3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
