/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ANeCond2 extends PCond2
{
    private PCond3 _cond3_;
    private TNe _ne_;
    private PCond2 _cond2_;

    public ANeCond2()
    {
        // Constructor
    }

    public ANeCond2(
        @SuppressWarnings("hiding") PCond3 _cond3_,
        @SuppressWarnings("hiding") TNe _ne_,
        @SuppressWarnings("hiding") PCond2 _cond2_)
    {
        // Constructor
        setCond3(_cond3_);

        setNe(_ne_);

        setCond2(_cond2_);

    }

    @Override
    public Object clone()
    {
        return new ANeCond2(
            cloneNode(this._cond3_),
            cloneNode(this._ne_),
            cloneNode(this._cond2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeCond2(this);
    }

    public PCond3 getCond3()
    {
        return this._cond3_;
    }

    public void setCond3(PCond3 node)
    {
        if(this._cond3_ != null)
        {
            this._cond3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond3_ = node;
    }

    public TNe getNe()
    {
        return this._ne_;
    }

    public void setNe(TNe node)
    {
        if(this._ne_ != null)
        {
            this._ne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ne_ = node;
    }

    public PCond2 getCond2()
    {
        return this._cond2_;
    }

    public void setCond2(PCond2 node)
    {
        if(this._cond2_ != null)
        {
            this._cond2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond3_)
            + toString(this._ne_)
            + toString(this._cond2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond3_ == child)
        {
            this._cond3_ = null;
            return;
        }

        if(this._ne_ == child)
        {
            this._ne_ = null;
            return;
        }

        if(this._cond2_ == child)
        {
            this._cond2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond3_ == oldChild)
        {
            setCond3((PCond3) newChild);
            return;
        }

        if(this._ne_ == oldChild)
        {
            setNe((TNe) newChild);
            return;
        }

        if(this._cond2_ == oldChild)
        {
            setCond2((PCond2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
