/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ANotCond4 extends PCond4
{
    private TNeg _neg_;
    private PCond4 _cond4_;

    public ANotCond4()
    {
        // Constructor
    }

    public ANotCond4(
        @SuppressWarnings("hiding") TNeg _neg_,
        @SuppressWarnings("hiding") PCond4 _cond4_)
    {
        // Constructor
        setNeg(_neg_);

        setCond4(_cond4_);

    }

    @Override
    public Object clone()
    {
        return new ANotCond4(
            cloneNode(this._neg_),
            cloneNode(this._cond4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotCond4(this);
    }

    public TNeg getNeg()
    {
        return this._neg_;
    }

    public void setNeg(TNeg node)
    {
        if(this._neg_ != null)
        {
            this._neg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._neg_ = node;
    }

    public PCond4 getCond4()
    {
        return this._cond4_;
    }

    public void setCond4(PCond4 node)
    {
        if(this._cond4_ != null)
        {
            this._cond4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._neg_)
            + toString(this._cond4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._neg_ == child)
        {
            this._neg_ = null;
            return;
        }

        if(this._cond4_ == child)
        {
            this._cond4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._neg_ == oldChild)
        {
            setNeg((TNeg) newChild);
            return;
        }

        if(this._cond4_ == oldChild)
        {
            setCond4((PCond4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
