/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ANotLastList extends PList
{
    private PVal _val_;
    private TComma _comma_;
    private PList _list_;

    public ANotLastList()
    {
        // Constructor
    }

    public ANotLastList(
        @SuppressWarnings("hiding") PVal _val_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PList _list_)
    {
        // Constructor
        setVal(_val_);

        setComma(_comma_);

        setList(_list_);

    }

    @Override
    public Object clone()
    {
        return new ANotLastList(
            cloneNode(this._val_),
            cloneNode(this._comma_),
            cloneNode(this._list_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotLastList(this);
    }

    public PVal getVal()
    {
        return this._val_;
    }

    public void setVal(PVal node)
    {
        if(this._val_ != null)
        {
            this._val_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._val_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PList getList()
    {
        return this._list_;
    }

    public void setList(PList node)
    {
        if(this._list_ != null)
        {
            this._list_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._list_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._val_)
            + toString(this._comma_)
            + toString(this._list_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._val_ == child)
        {
            this._val_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._list_ == child)
        {
            this._list_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._val_ == oldChild)
        {
            setVal((PVal) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._list_ == oldChild)
        {
            setList((PList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
