/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ANumType extends PType
{
    private TNumType _numType_;

    public ANumType()
    {
        // Constructor
    }

    public ANumType(
        @SuppressWarnings("hiding") TNumType _numType_)
    {
        // Constructor
        setNumType(_numType_);

    }

    @Override
    public Object clone()
    {
        return new ANumType(
            cloneNode(this._numType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumType(this);
    }

    public TNumType getNumType()
    {
        return this._numType_;
    }

    public void setNumType(TNumType node)
    {
        if(this._numType_ != null)
        {
            this._numType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numType_ == child)
        {
            this._numType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numType_ == oldChild)
        {
            setNumType((TNumType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
