/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ANumVal extends PVal
{
    private TNumval _numval_;

    public ANumVal()
    {
        // Constructor
    }

    public ANumVal(
        @SuppressWarnings("hiding") TNumval _numval_)
    {
        // Constructor
        setNumval(_numval_);

    }

    @Override
    public Object clone()
    {
        return new ANumVal(
            cloneNode(this._numval_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumVal(this);
    }

    public TNumval getNumval()
    {
        return this._numval_;
    }

    public void setNumval(TNumval node)
    {
        if(this._numval_ != null)
        {
            this._numval_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numval_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numval_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numval_ == child)
        {
            this._numval_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numval_ == oldChild)
        {
            setNumval((TNumval) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
