/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AOrCond extends PCond
{
    private PCond1 _cond1_;
    private TOr _or_;
    private PCond _cond_;

    public AOrCond()
    {
        // Constructor
    }

    public AOrCond(
        @SuppressWarnings("hiding") PCond1 _cond1_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PCond _cond_)
    {
        // Constructor
        setCond1(_cond1_);

        setOr(_or_);

        setCond(_cond_);

    }

    @Override
    public Object clone()
    {
        return new AOrCond(
            cloneNode(this._cond1_),
            cloneNode(this._or_),
            cloneNode(this._cond_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrCond(this);
    }

    public PCond1 getCond1()
    {
        return this._cond1_;
    }

    public void setCond1(PCond1 node)
    {
        if(this._cond1_ != null)
        {
            this._cond1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond1_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PCond getCond()
    {
        return this._cond_;
    }

    public void setCond(PCond node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond1_)
            + toString(this._or_)
            + toString(this._cond_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond1_ == child)
        {
            this._cond1_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond1_ == oldChild)
        {
            setCond1((PCond1) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._cond_ == oldChild)
        {
            setCond((PCond) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
