/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AReturEndblock extends PEndblock
{
    private TReturn _return_;
    private PVal _val_;
    private TRCurly _rCurly_;
    private TNewline _newline_;

    public AReturEndblock()
    {
        // Constructor
    }

    public AReturEndblock(
        @SuppressWarnings("hiding") TReturn _return_,
        @SuppressWarnings("hiding") PVal _val_,
        @SuppressWarnings("hiding") TRCurly _rCurly_,
        @SuppressWarnings("hiding") TNewline _newline_)
    {
        // Constructor
        setReturn(_return_);

        setVal(_val_);

        setRCurly(_rCurly_);

        setNewline(_newline_);

    }

    @Override
    public Object clone()
    {
        return new AReturEndblock(
            cloneNode(this._return_),
            cloneNode(this._val_),
            cloneNode(this._rCurly_),
            cloneNode(this._newline_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReturEndblock(this);
    }

    public TReturn getReturn()
    {
        return this._return_;
    }

    public void setReturn(TReturn node)
    {
        if(this._return_ != null)
        {
            this._return_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._return_ = node;
    }

    public PVal getVal()
    {
        return this._val_;
    }

    public void setVal(PVal node)
    {
        if(this._val_ != null)
        {
            this._val_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._val_ = node;
    }

    public TRCurly getRCurly()
    {
        return this._rCurly_;
    }

    public void setRCurly(TRCurly node)
    {
        if(this._rCurly_ != null)
        {
            this._rCurly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rCurly_ = node;
    }

    public TNewline getNewline()
    {
        return this._newline_;
    }

    public void setNewline(TNewline node)
    {
        if(this._newline_ != null)
        {
            this._newline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newline_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._return_)
            + toString(this._val_)
            + toString(this._rCurly_)
            + toString(this._newline_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._return_ == child)
        {
            this._return_ = null;
            return;
        }

        if(this._val_ == child)
        {
            this._val_ = null;
            return;
        }

        if(this._rCurly_ == child)
        {
            this._rCurly_ = null;
            return;
        }

        if(this._newline_ == child)
        {
            this._newline_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._return_ == oldChild)
        {
            setReturn((TReturn) newChild);
            return;
        }

        if(this._val_ == oldChild)
        {
            setVal((PVal) newChild);
            return;
        }

        if(this._rCurly_ == oldChild)
        {
            setRCurly((TRCurly) newChild);
            return;
        }

        if(this._newline_ == oldChild)
        {
            setNewline((TNewline) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
