/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AStmtStart extends PStart
{
    private PStmts _stmts_;

    public AStmtStart()
    {
        // Constructor
    }

    public AStmtStart(
        @SuppressWarnings("hiding") PStmts _stmts_)
    {
        // Constructor
        setStmts(_stmts_);

    }

    @Override
    public Object clone()
    {
        return new AStmtStart(
            cloneNode(this._stmts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtStart(this);
    }

    public PStmts getStmts()
    {
        return this._stmts_;
    }

    public void setStmts(PStmts node)
    {
        if(this._stmts_ != null)
        {
            this._stmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmts_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stmts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stmts_ == child)
        {
            this._stmts_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stmts_ == oldChild)
        {
            setStmts((PStmts) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
