/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AStmtsStart extends PStart
{
    private PStmts _stmts_;
    private PStart _start_;

    public AStmtsStart()
    {
        // Constructor
    }

    public AStmtsStart(
        @SuppressWarnings("hiding") PStmts _stmts_,
        @SuppressWarnings("hiding") PStart _start_)
    {
        // Constructor
        setStmts(_stmts_);

        setStart(_start_);

    }

    @Override
    public Object clone()
    {
        return new AStmtsStart(
            cloneNode(this._stmts_),
            cloneNode(this._start_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtsStart(this);
    }

    public PStmts getStmts()
    {
        return this._stmts_;
    }

    public void setStmts(PStmts node)
    {
        if(this._stmts_ != null)
        {
            this._stmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmts_ = node;
    }

    public PStart getStart()
    {
        return this._start_;
    }

    public void setStart(PStart node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stmts_)
            + toString(this._start_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stmts_ == child)
        {
            this._stmts_ = null;
            return;
        }

        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stmts_ == oldChild)
        {
            setStmts((PStmts) newChild);
            return;
        }

        if(this._start_ == oldChild)
        {
            setStart((PStart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
