/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AStrDcl extends PDcl
{
    private TStrType _strType_;
    private PAssignStmt _assignStmt_;

    public AStrDcl()
    {
        // Constructor
    }

    public AStrDcl(
        @SuppressWarnings("hiding") TStrType _strType_,
        @SuppressWarnings("hiding") PAssignStmt _assignStmt_)
    {
        // Constructor
        setStrType(_strType_);

        setAssignStmt(_assignStmt_);

    }

    @Override
    public Object clone()
    {
        return new AStrDcl(
            cloneNode(this._strType_),
            cloneNode(this._assignStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrDcl(this);
    }

    public TStrType getStrType()
    {
        return this._strType_;
    }

    public void setStrType(TStrType node)
    {
        if(this._strType_ != null)
        {
            this._strType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strType_ = node;
    }

    public PAssignStmt getAssignStmt()
    {
        return this._assignStmt_;
    }

    public void setAssignStmt(PAssignStmt node)
    {
        if(this._assignStmt_ != null)
        {
            this._assignStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strType_)
            + toString(this._assignStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strType_ == child)
        {
            this._strType_ = null;
            return;
        }

        if(this._assignStmt_ == child)
        {
            this._assignStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strType_ == oldChild)
        {
            setStrType((TStrType) newChild);
            return;
        }

        if(this._assignStmt_ == oldChild)
        {
            setAssignStmt((PAssignStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
