/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AStrType extends PType
{
    private TStrType _strType_;

    public AStrType()
    {
        // Constructor
    }

    public AStrType(
        @SuppressWarnings("hiding") TStrType _strType_)
    {
        // Constructor
        setStrType(_strType_);

    }

    @Override
    public Object clone()
    {
        return new AStrType(
            cloneNode(this._strType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrType(this);
    }

    public TStrType getStrType()
    {
        return this._strType_;
    }

    public void setStrType(TStrType node)
    {
        if(this._strType_ != null)
        {
            this._strType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strType_ == child)
        {
            this._strType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strType_ == oldChild)
        {
            setStrType((TStrType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
