/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AStrVal extends PVal
{
    private TStringval _stringval_;

    public AStrVal()
    {
        // Constructor
    }

    public AStrVal(
        @SuppressWarnings("hiding") TStringval _stringval_)
    {
        // Constructor
        setStringval(_stringval_);

    }

    @Override
    public Object clone()
    {
        return new AStrVal(
            cloneNode(this._stringval_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrVal(this);
    }

    public TStringval getStringval()
    {
        return this._stringval_;
    }

    public void setStringval(TStringval node)
    {
        if(this._stringval_ != null)
        {
            this._stringval_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringval_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringval_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringval_ == child)
        {
            this._stringval_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringval_ == oldChild)
        {
            setStringval((TStringval) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
