/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AUnaryCond3 extends PCond3
{
    private PCond4 _cond4_;

    public AUnaryCond3()
    {
        // Constructor
    }

    public AUnaryCond3(
        @SuppressWarnings("hiding") PCond4 _cond4_)
    {
        // Constructor
        setCond4(_cond4_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryCond3(
            cloneNode(this._cond4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryCond3(this);
    }

    public PCond4 getCond4()
    {
        return this._cond4_;
    }

    public void setCond4(PCond4 node)
    {
        if(this._cond4_ != null)
        {
            this._cond4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond4_ == child)
        {
            this._cond4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond4_ == oldChild)
        {
            setCond4((PCond4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
