/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AVoidEndblock extends PEndblock
{
    private TRCurly _rCurly_;
    private TNewline _newline_;

    public AVoidEndblock()
    {
        // Constructor
    }

    public AVoidEndblock(
        @SuppressWarnings("hiding") TRCurly _rCurly_,
        @SuppressWarnings("hiding") TNewline _newline_)
    {
        // Constructor
        setRCurly(_rCurly_);

        setNewline(_newline_);

    }

    @Override
    public Object clone()
    {
        return new AVoidEndblock(
            cloneNode(this._rCurly_),
            cloneNode(this._newline_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVoidEndblock(this);
    }

    public TRCurly getRCurly()
    {
        return this._rCurly_;
    }

    public void setRCurly(TRCurly node)
    {
        if(this._rCurly_ != null)
        {
            this._rCurly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rCurly_ = node;
    }

    public TNewline getNewline()
    {
        return this._newline_;
    }

    public void setNewline(TNewline node)
    {
        if(this._newline_ != null)
        {
            this._newline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newline_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rCurly_)
            + toString(this._newline_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rCurly_ == child)
        {
            this._rCurly_ = null;
            return;
        }

        if(this._newline_ == child)
        {
            this._newline_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rCurly_ == oldChild)
        {
            setRCurly((TRCurly) newChild);
            return;
        }

        if(this._newline_ == oldChild)
        {
            setNewline((TNewline) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
