/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TListDcl extends Token
{
    public TListDcl()
    {
        super.setText("[]");
    }

    public TListDcl(int line, int pos)
    {
        super.setText("[]");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TListDcl(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTListDcl(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TListDcl text.");
    }
}
