/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TNumType extends Token
{
    public TNumType()
    {
        super.setText("num");
    }

    public TNumType(int line, int pos)
    {
        super.setText("num");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNumType(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNumType(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNumType text.");
    }
}
